/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Choose wether to use the light version of the Header
 */
export type LightVersion = boolean;
/**
 * Link to the home page used on the logo
 */
export type LinkToHomePage = string;
/**
 * Wether to show the navigation in Header
 */
export type EnableNavigation = boolean;
/**
 * Label for the navigation entry
 */
export type LabelForEntry = string;
/**
 * Link target for the navigation entry
 */
export type LinkTargetForEntry = string;
/**
 * Label for the navigation entry, used to mark the active entry
 */
export type SlugForEntry = string;
/**
 * Navigation entries displayed in the Header menu
 */
export type NavigationEntries = {
  label: LabelForEntry;
  href: LinkTargetForEntry;
  id: SlugForEntry;
  [k: string]: unknown;
}[];
/**
 * Slug of the current page, to mark it in the Header menu
 */
export type ActiveNavigationEntry = string;
/**
 * Enter the label for the button
 */
export type LabelForButton = string;
/**
 * Enter the link target for the button
 */
export type LinkTargetForButton = string;

/**
 * Header to be used in website layouts
 */
export interface HeaderProps {
  light?: LightVersion;
  homeLink: LinkToHomePage;
  navEnabled?: EnableNavigation;
  navEntries?: NavigationEntries;
  activeEntry: ActiveNavigationEntry;
  cta?: CallToAction;
  [k: string]: unknown;
}
/**
 * Label and target for the Header button
 */
export interface CallToAction {
  label: LabelForButton;
  href: LinkTargetForButton;
  [k: string]: unknown;
}
