/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */
export declare type TwitterHandle = string;
export declare type PhoneNumber = "";
/**
 * Picture source
 */
export declare type Source = string;
/**
 * Use a srcSet to display picture
 */
export declare type PictureSourceset = string;
/**
 * Alt text to display for picture
 */
export declare type AltText = string;
/**
 * Width of the picture
 */
export declare type Width = number;
/**
 * Height of the picture
 */
export declare type Height = number;
/**
 * Add additional css classes that should be applied to the button
 */
export declare type AdditionalClasses = string;
/**
 * Add id attribute to the image
 */
export declare type Id = string;
/**
 * Define an itemprop attribute for the picture
 */
export declare type ItempropAttribute = string;
/**
 * Define a style attribute for the picture
 */
export declare type StyleAttribute = string;
/**
 * Select a value for the picture object fit
 */
export declare type ObjectFit = "contain" | "cover" | "fill" | "none" | "scale-down";
/**
 * Render noscript fallback
 */
export declare type Noscript = boolean;
/**
 * Load the picture lazily
 */
export declare type Lazy = boolean;
/**
 * Use a srcSet to display picture
 */
export declare type PictureSourceset1 = string;
/**
 * TODO MEDIA DESCRIPTION
 */
export declare type TODOMEDIATITLE = string;
/**
 * TODO TYPE DESCRIPTION
 */
export declare type TODOTYPETITLE = string;
/**
 * Additional sources. This will result in a `picture`-Element
 */
export declare type Sources = {
    srcSet?: PictureSourceset1;
    media?: TODOMEDIATITLE;
    type?: TODOTYPETITLE;
    [k: string]: unknown;
}[];
/**
 * Set additional class(es) to the picture
 */
export declare type ClassAttribute = string;
/**
 * Name, company name, etc.
 */
export declare type Title = string;
/**
 * Position, profession, department, location, etc.
 */
export declare type Subtitle = string;
export declare type EmailAddress = string;
export declare type CopyText = string;
/**
 * Additional css classes attached to the wrapping element
 */
export declare type Class = string;
/**
 * Component to show contact information
 */
export interface ContactProps {
    twitter?: TwitterHandle;
    phone?: PhoneNumber;
    image?: Picture;
    title?: Title;
    subtitle?: Subtitle;
    email?: EmailAddress;
    copy?: CopyText;
    className?: Class;
    [k: string]: unknown;
}
/**
 * Base component to display a picture
 */
export interface Picture {
    src?: Source;
    srcSet?: PictureSourceset;
    alt?: AltText;
    width?: Width;
    height?: Height;
    className?: AdditionalClasses;
    id?: Id;
    itemProp?: ItempropAttribute;
    style?: StyleAttribute;
    objectFit?: ObjectFit;
    noscript?: Noscript;
    lazy?: Lazy;
    sources?: Sources;
    pictureClassName?: ClassAttribute;
    [k: string]: unknown;
}
