version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:14.15
  working_directory: /mnt/ramdisk
  resource_class: medium+

aliases:
  - &save-cache-yarn
    key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - .yarn-cache
  - &restore-cache-yarn
    keys:
      - yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - yarn-{{ checksum "yarn.lock" }}
      - yarn-
  - &save-cache-node
    key: node-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
    paths:
      - node_modules
  - &restore-cache-node
    keys:
      - node-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
      - node-{{ checksum "yarn.lock" }}
      - node-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-yarn
      - restore_cache: *restore-cache-node
      - run:
          name: Set Yarn Cache Directory
          command: yarn config set cache-folder /mnt/ramdisk/.yarn-cache
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder /mnt/ramdisk/.yarn-cache
      - save_cache: *save-cache-yarn
      - save_cache: *save-cache-node

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - run:
          name: Create Release
          command: yarn auto shipit

  chromatic:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - run:
          name: Deploy Storybook
          command: yarn chromatic

  chromatic_and_netlify:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-node
      - run:
          name: Deploy Storybook
          command: yarn chromatic
      - run:
          name: Rename dist folder
          command: mv storybook-static storybook
      - run:
          name: Zip dist folder
          command: tar -czf storybook.tar.gz storybook
      - store_artifacts:
          path: storybook.tar.gz
      - run:
          name: Deploy Netlify
          command: yarn netlify deploy --prod --dir=storybook

  update_website:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger website upgrade
          command: |
            curl --request POST \
              --url https://circleci.com/api/v2/project/gh/kickstartDS/website/pipeline \
              --header "Circle-Token: ${CIRCLE_CI_WEBSITE_BUILD_TOKEN}" \
              --header 'content-type: application/json' \
              --data '{"branch":"master","parameters":{"run_workflow_update":true}}'

workflows:
  release:
    jobs:
      - install

      - release:
          context: kickstartDS
          requires:
            - install

      - update_website:
          context: kickstartDS
          filters:
            branches:
              only: master
          requires:
            - release

      - chromatic:
          filters:
            branches:
              ignore: master
          requires:
            - install

      - chromatic_and_netlify:
          filters:
            branches:
              only: master
          requires:
            - install
