/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Link to the appearance
 */
export type LinkToAppearance = string;
/**
 * Title that should be shown for this appearance
 */
export type TitleForTheAppearance = string;
/**
 * Description of the type and content of the appearance
 */
export type DescriptionOfTheAppearance = string;
/**
 * Name of the host
 */
export type Name = string;
/**
 * URL to get to the web presence of the host
 */
export type Link = string;
/**
 * Who participated in this appearance?
 */
export type Participants = [Person, ...Person[]];
/**
 * The displayed name of the person
 */
export type Name1 = string;
/**
 * The avatar of the person
 */
export type Avatar = string;
/**
 * The titles of a person
 */
export type Title = string;
/**
 * Set the size of the person component
 */
export type Size = "s" | "m" | "l";
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;
/**
 * Name of the tag
 */
export type Tag = string;
/**
 * Tags for this showcase entry
 */
export type Tags = Tag[];
/**
 * Date the appearance occurred
 */
export type Date = string;
/**
 * Primary language the appearance was in
 */
export type Language = "English" | "German";
/**
 * Url to main image for this appearance entry
 */
export type Url = string;
/**
 * Title of the appearance cover
 */
export type Caption = string;
/**
 * Select a media asset for this appearance entry
 */
export type UrlForTheMediaAsset = string;
/**
 * Title of the appearance image
 */
export type CaptionForTheImage = string;
/**
 * Media assets to display for this appearance entry
 */
export type Media = MediaAsset[];
/**
 * Title of the related appearance
 */
export type Title1 = string;
/**
 * Excerpt for the related appearance
 */
export type Excerpt = string;
/**
 * Url for the related appearance
 */
export type Url1 = string;
/**
 * Type of content that is being teased
 */
export type Type = string;
/**
 * Image for the related appearance
 */
export type Image = string;
/**
 * Name of the tag
 */
export type Tag1 = string;
/**
 * Tags for this related teaser
 */
export type Tags1 = Tag1[];
/**
 * Entries related to this appearance entry
 */
export type RelatedEntries = Related[];

/**
 * Display one appearance entry with all its details
 */
export interface AppearanceProps {
  link: LinkToAppearance;
  title: TitleForTheAppearance;
  description: DescriptionOfTheAppearance;
  host: HostOfTheAppearance;
  participants: Participants;
  tags?: Tags;
  date: Date;
  language?: Language;
  cover: CoverImage;
  media?: Media;
  related?: RelatedEntries;
  [k: string]: unknown;
}
/**
 * The party hosting the appearance, may be a podcast, company or individual
 */
export interface HostOfTheAppearance {
  name?: Name;
  url?: Link;
  [k: string]: unknown;
}
/**
 * A preview of a person with name and an avatar image
 */
export interface Person {
  name: Name1;
  avatar?: Avatar;
  title?: Title;
  size: Size;
  className?: Class;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}
/**
 * Add main image to represent this appearance entry
 */
export interface CoverImage {
  src: Url;
  caption: Caption;
  [k: string]: unknown;
}
/**
 * Single media asset
 */
export interface MediaAsset {
  src?: UrlForTheMediaAsset;
  caption?: CaptionForTheImage;
  [k: string]: unknown;
}
/**
 * A preview of contextually relevant content
 */
export interface Related {
  title: Title1;
  excerpt: Excerpt;
  url: Url1;
  type?: Type;
  image: Image;
  tags?: Tags1;
  [k: string]: unknown;
}
