/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Link to the appearance
 */
export type LinkToAppearance = string;
/**
 * Title that should be shown for this appearance
 */
export type TitleForTheAppearance = string;
/**
 * Description of the type and content of the appearance
 */
export type DescriptionOfTheAppearance = string;
/**
 * Name of the host
 */
export type Name = string;
/**
 * URL to get to the web presence of the host
 */
export type Link = string;
/**
 * Who participated in this appearance?
 */
export type Participants = [string, ...string[]];
/**
 * Date the appearance occurred
 */
export type Date = string;
/**
 * Primary language the appearance was in
 */
export type Language = "English" | "German";
/**
 * Url to main image for this appearance entry
 */
export type Url = string;
/**
 * Title of the appearance cover
 */
export type Caption = string;
/**
 * Select a media asset for this appearance entry
 */
export type UrlForTheMediaAsset = string;
/**
 * Title of the appearance image
 */
export type CaptionForTheImage = string;
/**
 * Media assets to display for this appearance entry
 */
export type Media = MediaAsset[];
/**
 * Name of the tag
 */
export type Tag = string;
/**
 * Tags for this appearance entry
 */
export type Tags = Tag[];
/**
 * Title of the related appearance
 */
export type Title = string;
/**
 * Excerpt for the related appearance
 */
export type Excerpt = string;
/**
 * Url for the related appearance
 */
export type Url1 = string;
/**
 * Image for the related appearance
 */
export type Image = string;
/**
 * Entries related to this appearance entry
 */
export type RelatedEntries = RelatedEntry[];

/**
 * Display one appearance entry with all its details
 */
export interface AppearanceProps {
  link: LinkToAppearance;
  title: TitleForTheAppearance;
  description: DescriptionOfTheAppearance;
  host: HostOfTheAppearance;
  participants: Participants;
  date: Date;
  language?: Language;
  cover: CoverImage;
  media?: Media;
  tags?: Tags;
  related?: RelatedEntries;
  [k: string]: unknown;
}
/**
 * The party hosting the appearance, may be a podcast, company or individual
 */
export interface HostOfTheAppearance {
  name?: Name;
  url?: Link;
  [k: string]: unknown;
}
/**
 * Add main image to represent this appearance entry
 */
export interface CoverImage {
  src: Url;
  caption: Caption;
  [k: string]: unknown;
}
/**
 * Single media asset
 */
export interface MediaAsset {
  src?: UrlForTheMediaAsset;
  caption?: CaptionForTheImage;
  [k: string]: unknown;
}
/**
 * Single related entry
 */
export interface RelatedEntry {
  title: Title;
  excerpt?: Excerpt;
  url: Url1;
  image?: Image;
  [k: string]: unknown;
}
