/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */
/**
 * Select the headline level to use, or p alternatively
 */
export declare type Level = "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Select the headline style to use
 */
export declare type Style = "none" | "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Choose an alignment for the headline
 */
export declare type Alignment = "left" | "center" | "right";
/**
 * Text content for the headline
 */
export declare type Text = string;
/**
 * Text content for the optional subheadline
 */
export declare type Subheadline = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export declare type BottomSpacing = "none" | "small" | "large";
/**
 * Set the headline as a page header, triggering special css treatment
 */
export declare type PageHeader = boolean;
/**
 * Add additional css classes that should be applied to the headline
 */
export declare type AdditionalClasses = string;
/**
 * Headline
 */
export interface HeadlineProps {
    level: Level;
    styleAs?: Style;
    align: Alignment;
    content?: Text;
    subheadline?: Subheadline;
    spaceAfter: BottomSpacing;
    pageHeader?: PageHeader;
    className?: AdditionalClasses;
    /**
     * Show subheadline first
     */
    switchOrder?: boolean;
    [k: string]: unknown;
}
