declare module "@kickstartds/blog/lib/post-aside/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {PictureProps} from "@kickstartds/base/lib/picture/typing";
import type {PostMetaProps} from "@kickstartds/blog/lib/post-meta/typing";
import type {PostShareBarProps} from "@kickstartds/blog/lib/post-share-bar/typing";

/**
 * Select the headline level to use, or p alternatively
 */
export type Level = "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Select the headline style to use
 */
export type Style = "none" | "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Choose an alignment for the headline
 */
export type Alignment = "left" | "center" | "right";
/**
 * Text content for the headline
 */
export type Text = string;
/**
 * Text content for the optional subheadline
 */
export type Subheadline = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export type BottomSpacing = "minimum" | "small" | "large";
/**
 * Add additional css classes that should be applied to the headline
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;
/**
 * Name, company name, etc.
 */
export type Title = string;
/**
 * Position, profession, department, location, etc.
 */
export type Subtitle = string;
/**
 * Open link in new Tab
 */
export type OpenLinkInNewTab = boolean;
export type CopyText = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute1 = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class1 = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute2 = string;

/**
 * Post Aside
 */
export interface PostAsideProps {
  author?: Contact;
  /**
   * Referenced component PostMetaProps
   */
  meta?: PostMetaProps;
  /**
   * Referenced component PostShareBarProps
   */
  shareBar?: PostShareBarProps;
  className?: Class1;
  component?: KsComponentAttribute2;
}
/**
 * Component to show contact information
 */
export interface Contact {
  headline?: Headline;
  /**
   * Referenced component PictureProps
   */
  image?: PictureProps;
  title?: Title;
  subtitle?: Subtitle;
  links?: {
    icon?: string;
    label?: string;
    href?: string;
    newTab?: OpenLinkInNewTab;
  }[];
  copy?: CopyText;
  className?: Class;
  component?: KsComponentAttribute1;
}
export interface Headline {
  /**
   * Show subheadline first
   */
  switchOrder?: boolean;
  level?: Level;
  styleAs?: Style;
  align?: Alignment;
  content?: Text;
  subheadline?: Subheadline;
  spaceAfter?: BottomSpacing;
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}

}
      