declare module "@kickstartds/blog/lib/post-share-bar/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Select the headline level to use, or p alternatively
 */
export type Level = "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Select the headline style to use
 */
export type Style = "none" | "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Choose an alignment for the headline
 */
export type Alignment = "left" | "center" | "right";
/**
 * Text content for the headline
 */
export type Headline1 = Headline2 & Headline3;
/**
 * Select the headline level to use, or p alternatively
 */
export type Level1 = "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Select the headline style to use
 */
export type Style1 = "none" | "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Choose an alignment for the headline
 */
export type Alignment1 = "left" | "center" | "right";
/**
 * Text content for the headline
 */
export type Text = string;
/**
 * Text content for the optional subheadline
 */
export type Subheadline = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export type BottomSpacing = "minimum" | "small" | "large";
/**
 * Add additional css classes that should be applied to the headline
 */
export type AdditionalClasses = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;
export type Headline3 = string;
/**
 * Text content for the optional subheadline
 */
export type Subheadline1 = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export type Headline4 = Headline5 & Headline6;
/**
 * Select the headline level to use, or p alternatively
 */
export type Level2 = "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Select the headline style to use
 */
export type Style2 = "none" | "h1" | "h2" | "h3" | "h4" | "h5" | "p";
/**
 * Choose an alignment for the headline
 */
export type Alignment2 = "left" | "center" | "right";
/**
 * Text content for the headline
 */
export type Text1 = string;
/**
 * Text content for the optional subheadline
 */
export type Subheadline2 = string;
/**
 * Add additional spacing to the bottom of the headline
 */
export type BottomSpacing1 = "minimum" | "small" | "large";
/**
 * Add additional css classes that should be applied to the headline
 */
export type AdditionalClasses1 = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute1 = string;
export type Headline6 = "minimum" | "small" | "large";
/**
 * Add additional css classes that should be applied to the headline
 */
export type AdditionalClasses2 = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute2 = string;
/**
 * Open link in new Tab
 */
export type OpenLinkInNewTab = boolean;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute3 = string;

/**
 * Post Share Bar
 */
export interface PostShareBarProps {
  headline?: Headline;
  links?: ShareLink[];
  className?: Class;
  component?: KsComponentAttribute3;
}
export interface Headline {
  /**
   * Show subheadline first
   */
  switchOrder?: boolean;
  level?: Level;
  styleAs?: Style;
  align?: Alignment;
  content?: Headline1;
  subheadline?: Subheadline1;
  spaceAfter?: Headline4;
  className?: AdditionalClasses2;
  component?: KsComponentAttribute2;
  [k: string]: unknown;
}
export interface Headline2 {
  /**
   * Show subheadline first
   */
  switchOrder?: boolean;
  level?: Level1;
  styleAs?: Style1;
  align?: Alignment1;
  content?: Text;
  subheadline?: Subheadline;
  spaceAfter?: BottomSpacing;
  className?: AdditionalClasses;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}
export interface Headline5 {
  /**
   * Show subheadline first
   */
  switchOrder?: boolean;
  level?: Level2;
  styleAs?: Style2;
  align?: Alignment2;
  content?: Text1;
  subheadline?: Subheadline2;
  spaceAfter?: BottomSpacing1;
  className?: AdditionalClasses1;
  component?: KsComponentAttribute1;
  [k: string]: unknown;
}
export interface ShareLink {
  href?: string;
  icon?: string;
  title?: string;
  newTab?: OpenLinkInNewTab;
  [k: string]: unknown;
}

}
      