/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Choose wether to use the dark version of the Logo
 */
export type DarkVersion = boolean;
/**
 * Link to the home page used on the logo
 */
export type LinkToHomePage = string;

export interface LogoProps {
  dark?: DarkVersion;
  homeLink?: LinkToHomePage;
  [k: string]: unknown;
}
