/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * The displayed name of the person
 */
export type Name = string;
/**
 * The avatar of the person
 */
export type Avatar = string;
/**
 * The titles of a person
 */
export type Title = string;
/**
 * Set the size of the person component
 */
export type Size = "s" | "m" | "l";
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;

/**
 * A preview of a person with name and an avatar image
 */
export interface PersonProps {
  name: Name;
  avatar?: Avatar;
  title?: Title;
  size: Size;
  className?: Class;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}
