/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Title of the Source
 */
export type Title = string;
/**
 * Text excerpt
 */
export type Text = string;

/**
 * Display one showcase entry with all its details
 */
export interface SourceSnippetProps {
  title: Title;
  text?: Text;
  [k: string]: unknown;
}
