/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Title of the related appearance
 */
export type Title = string;
/**
 * Excerpt for the related appearance
 */
export type Excerpt = string;
/**
 * Url for the related appearance
 */
export type Url = string;
/**
 * Type of content that is being teased
 */
export type Type = string;
/**
 * Image for the related appearance
 */
export type Image = string;
/**
 * Name of the tag
 */
export type Tag = string;
/**
 * Tags for this related teaser
 */
export type Tags = Tag[];

/**
 * A preview of contextually relevant content
 */
export interface RelatedProps {
  title: Title;
  excerpt: Excerpt;
  url: Url;
  type?: Type;
  image: Image;
  tags?: Tags;
  [k: string]: unknown;
}
