/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Link to the showcase / example / demo project
 */
export type LinkToShowcase = string;
/**
 * Title that should be shown for this appearance
 */
export type TitleForTheShowcase = string;
/**
 * Title that should be shown for this appearance
 */
export type ShortSummaryOfTheShowcase = string;
/**
 * Enable/Disable Quote element
 */
export type QuoteToggle = boolean;
/**
 * Select an image to display inside the quote, to the left
 */
export type ImageSource = string;
/**
 * Copy text for the element
 */
export type TextContent = string;
/**
 * Optionally display the source for the quote
 */
export type Source = string;
/**
 * Optionally display a byline for the quote's source
 */
export type SourceAddition = string;
/**
 * Additional css classes attached to the wrapping element
 */
export type Class = string;
/**
 * Optional custom component identifier
 */
export type KsComponentAttribute = string;
/**
 * Description of the type and content of the appearance
 */
export type DescriptionOfTheAppearance = string;
/**
 * Url to main image for this showcase entry
 */
export type Url = string;
/**
 * Title of the showcase cover
 */
export type Caption = string;
/**
 * Select a media asset for this showcase entry
 */
export type UrlForTheMediaAsset = string;
/**
 * Title of the showcase image
 */
export type CaptionForTheImage = string;
/**
 * Media assets to display for this showcase entry
 */
export type Media = MediaAsset[];
/**
 * Text to display inside tag label
 */
export type Label = string;
/**
 * Set optional href to link the tag
 */
export type LinkTarget = string;
/**
 * Tags for this showcase entry
 */
export type Tags = TagLabel[];
/**
 * Type of content that is being teased
 */
export type Type = string;
/**
 * Title of the related appearance
 */
export type Title = string;
/**
 * Excerpt for the related appearance
 */
export type Excerpt = string;
/**
 * Url for the related appearance
 */
export type Url1 = string;
/**
 * Image for the related appearance
 */
export type Image = string;
/**
 * Text to display inside tag label
 */
export type Label1 = string;
/**
 * Set optional href to link the tag
 */
export type LinkTarget1 = string;
/**
 * Tags for this related teaser
 */
export type Tags1 = TagLabel1[];
/**
 * Entries related to this appearance entry
 */
export type RelatedEntries = Related[];
/**
 * Overview page for all showcase entries
 */
export type OverviewPage = string;

/**
 * Display one showcase entry with all its details
 */
export interface ShowcaseProps {
  link: LinkToShowcase;
  title: TitleForTheShowcase;
  summary?: ShortSummaryOfTheShowcase;
  quote?: QuoteElement;
  description: DescriptionOfTheAppearance;
  cover: CoverImage;
  media?: Media;
  tags?: Tags;
  related?: RelatedEntries;
  overviewPage: OverviewPage;
  [k: string]: unknown;
}
/**
 * Quote that should be shown for this appearance
 */
export interface QuoteElement {
  quoteToggle?: QuoteToggle;
  image?: ImageSource;
  text: TextContent;
  source?: Source;
  byline?: SourceAddition;
  className?: Class;
  component?: KsComponentAttribute;
  [k: string]: unknown;
}
/**
 * Add main image to represent this showcase entry
 */
export interface CoverImage {
  src?: Url;
  caption?: Caption;
  [k: string]: unknown;
}
/**
 * Single media asset
 */
export interface MediaAsset {
  mode?: "image" | "video";
  src?: UrlForTheMediaAsset;
  caption?: CaptionForTheImage;
  [k: string]: unknown;
}
/**
 * Component to render a pill / tag / label
 */
export interface TagLabel {
  label?: Label;
  link?: LinkTarget;
  [k: string]: unknown;
}
/**
 * A preview of contextually relevant content
 */
export interface Related {
  typeLabel?: Type;
  title: Title;
  excerpt: Excerpt;
  url: Url1;
  image: Image;
  tags?: Tags1;
  [k: string]: unknown;
}
/**
 * Component to render a pill / tag / label
 */
export interface TagLabel1 {
  label?: Label1;
  link?: LinkTarget1;
  [k: string]: unknown;
}
